### ISSUE TITLE
Transform a org-file

### ISSUE THREAD

**Issue by domingoUnican** [legalnonsense/elgantt#1]
First of all, thank you for sharing your work.
I want to ask if it is possible to generate a Gantt diagram from a particular org-file. 
What it works is to set the org-agenda-files to the file I want to convert, but is it possible
to do this automatically?

**Comment by legalnonsense** [comment]
I just saw this. 

By default, it will use your agenda files to generate the chart, which you can set manually with (setq elgantt-agenda-files 'agenda)

To generate the chart from a particular file: (setq elgantt-agenda-files '("file-path")). 

There are new bugs I've noticed with the year change (and many old ones), so to be usable you'll also want to (setq elgantt-hide-previous-months nil) for now. Hoping to get this buggy mess cleaned up in the new year so it's actually usable by someone other than me.
