### ISSUE TITLE
how can we use this on current .org file each time?

### ISSUE THREAD

**Issue by michaelsjackson** [legalnonsense/elgantt#15]
This would give us freedom to apply the chart to any .org file.

**Comment by legalnonsense** [comment]
Just write a function that sets the value of `elgantt-agenda-files` before you call `(elgantt-open)`. Simple approach (which does not check to make sure it's an org file, or that the file is saved) would be:
```
(defun elgantt-open-current-org-file ()
  (setq elgantt-agenda-files (buffer-file-name))
  (elgantt-open))
```

**Comment by michaelsjackson** [comment]
Wonderful, thanks, working great after adding (interactive) at the top.

Another question can your tool also be used for time wise planning within a day?
So everything character could represent some amount of minutes one could set, or fixed like 5 minutes? My smallest amount of planning minutes would be 5, thus gave this example.
Example scenario would be planning a meeting, or lectures maybe?

If org-mode schedule feature allows minute granularity it should be possible I guess.  Maybe worth considering as well.  Thanks again. Have a nice day.  And cool you shared your great work.

**Comment by legalnonsense** [comment]
I am glad you find some use for it. I over designed it on purpose hoping others could use it. 

Other people have requested that but it's not a feature I'd find useful at this point so not planning to work on it. I'd rather focus on getting this code polished enough for melpa. But I will keep it in mind if and when I do more work on this. Meanwhile, you might want to check out https://github.com/Fuco1/org-timeline.
